/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans:  ['"Syne"', 'system-ui', 'sans-serif'],
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
      },

      // Custom color scheme generated by AI 
      colors: {
        ink: {
          950: '#0C0C0E',
          900: '#141416',
          800: '#1F1E22',
          700: '#2C2A30',
          600: '#3D3A43',
          500: '#5A5660',
          400: '#7C7882',
          300: '#9C98A5',
          200: '#C8C4CF',
          100: '#EDE8DF',
        },
        gold: {
          DEFAULT: '#C9A55A',
          light:   '#E0C07A',
          dim:     '#7A6335',
        },
      },
    },
  },
  plugins: [],
}
