# hardcoded data generated by ai writer for testing

DOCUMENTS: list[dict] = [
    {
        "id": "doc-1",
        "title": "Non-Disclosure and Employment Agreement — Umbrella Corp",
        "source": "Nothing Corp HR Dept, 2023",
        "full_text": (
            "NON-DISCLOSURE AND EMPLOYMENT AGREEMENT\n\n"
            "This Non-Disclosure and Employment Agreement ('Agreement') is entered into "
            "as of January 1, 2023, between Umbrella Corp ('Employer') and the undersigned "
            "employee ('Employee').\n\n"
            "1. CONFIDENTIALITY. Employee agrees to hold in strict confidence all "
            "proprietary information, trade secrets, client lists, and internal processes "
            "of Employer both during and after the term of employment. Disclosure of "
            "confidential information to any third party without prior written consent "
            "is strictly prohibited.\n\n"
            "2. NON-COMPETE. For a period of twelve (12) months following termination, "
            "Employee shall not engage in any business activity that directly competes "
            "with Employer within the same geographic market.\n\n"
            "3. INTELLECTUAL PROPERTY. All inventions, designs, software, or works "
            "created by Employee during the course of employment shall be the exclusive "
            "property of Employer.\n\n"
            "4. TERMINATION. Either party may terminate this agreement with thirty (30) "
            "days written notice. Obligations under Section 1 and 2 survive termination.\n\n"
            "5. GOVERNING LAW. This Agreement shall be governed by the laws of the "
            "State of Delaware."
        ),
    },
    {
        "id": "doc-2",
        "title": "Residential Lease Agreement — 412 Elmwood Drive",
        "source": "Greenfield Property Management, 2024",
        "full_text": (
            "RESIDENTIAL LEASE AGREEMENT\n\n"
            "This Residential Lease Agreement ('Lease') is made effective February 1, 2024, "
            "between Greenfield Property Management ('Landlord') and the undersigned "
            "tenant(s) ('Tenant') for the property located at 412 Elmwood Drive.\n\n"
            "1. LEASE TERM. The lease term begins February 1, 2024 and ends January 31, 2025 "
            "(12 months). Upon expiration, tenancy converts to month-to-month unless renewed "
            "in writing.\n\n"
            "2. RENT. Tenant agrees to pay $1,850 per month, due on the 1st of each month. "
            "A late fee of $75 applies after a 5-day grace period.\n\n"
            "3. SECURITY DEPOSIT. A security deposit of $3,700 (two months' rent) is due "
            "upon signing. It will be returned within 30 days of move-out, less any deductions "
            "for damages beyond normal wear and tear.\n\n"
            "4. MAINTENANCE. Tenant is responsible for routine upkeep including lawn care, "
            "replacing light bulbs, and keeping drains clear. Landlord is responsible for "
            "structural repairs and appliance maintenance.\n\n"
            "5. EARLY TERMINATION. If Tenant vacates before the lease end date, a penalty "
            "equal to two months' rent ($3,700) is due, in addition to forfeiture of the "
            "security deposit.\n\n"
            "6. GOVERNING LAW. This Lease is governed by the laws of the State of Ohio."
        ),
    },
    {
        "id": "doc-3",
        "title": "Privacy Policy and Data Protection Notice — Nexus Platform",
        "source": "Nexus Technologies LLC, 2024",
        "full_text": (
            "PRIVACY POLICY AND DATA PROTECTION NOTICE\n\n"
            "Effective Date: March 1, 2024. Nexus Technologies LLC ('Company') operates "
            "the Nexus Platform and is committed to protecting your personal data.\n\n"
            "1. DATA WE COLLECT. We collect information you provide directly (name, email, "
            "payment details) and data generated by your use of the platform (log files, "
            "IP addresses, device identifiers, cookies, and usage analytics).\n\n"
            "2. HOW WE USE YOUR DATA. Collected data is used to provide and improve our "
            "services, personalise your experience, process transactions, and send "
            "service-related communications.\n\n"
            "3. THIRD-PARTY SHARING. We may share data with trusted processors (payment "
            "gateways, cloud hosting providers, analytics vendors) under strict data "
            "processing agreements. We do not sell personal data.\n\n"
            "4. COOKIES. We use essential, functional, and analytics cookies. You may "
            "manage cookie preferences via your browser settings or our consent banner.\n\n"
            "5. DATA RETENTION. Personal data is retained for up to 36 months after your "
            "last active session, after which it is securely deleted or anonymised.\n\n"
            "6. YOUR RIGHTS (GDPR/UK GDPR). If you are located in the EU or UK, you have "
            "the right to access, rectify, erase, restrict, or port your personal data. "
            "Submit requests to privacy@nexusplatform.io.\n\n"
            "7. CONSENT. By using the platform, you consent to the terms of this policy."
        ),
    },
]
